### ISSUE TITLE
Possible syntax error in `*M208` in `artfugue-019.krn`

### ISSUE THREAD

**Issue by bel28kent** [craigsapp/art-of-the-fugue#1]
Is `*M208` in Contrapunctus 19 a syntax error, or have some meaning related to metronome markings? Currently, it is unknown by `tandeminfo`.

<img width="636" alt="Screen Shot 2024-08-18 at 1 46 36 PM" src="https://github.com/user-attachments/assets/61951df7-e801-4b6c-8c39-f21ba7227412">

**Comment by craigsapp** [comment]
Yes, that is a syntax error.   Those are the only two unknown interpretations in that repository:

```bash
$ tandeminfo -ufm *.krn
artfugue-019.krn	*M208	unknown
artfugue-019.krn	*M208	unknown
```

Now fixed.
